[
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 1,
    winnerTo: 13,
    loserTo: 9,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 2,
    winnerTo: 13,
    loserTo: 9,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 3,
    winnerTo: 14,
    loserTo: 10,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 4,
    winnerTo: 14,
    loserTo: 10,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 5,
    winnerTo: 15,
    loserTo: 11,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 6,
    winnerTo: 15,
    loserTo: 11,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 7,
    winnerTo: 16,
    loserTo: 12,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Winners Round of 16",
    wBracket: true,
    lBracket: false,
    round: 1,
    id: 8,
    winnerTo: 16,
    loserTo: 12,
    source: {
      winnerSources: [],
      loserSources: [],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 1,
    id: 9,
    winnerTo: 17,
    source: {
      winnerSources: [],
      loserSources: [1, 2],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 1,
    id: 10,
    winnerTo: 18,
    source: {
      winnerSources: [],
      loserSources: [3, 4],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 1,
    id: 11,
    winnerTo: 19,
    source: {
      winnerSources: [],
      loserSources: [5, 6],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 1,
    id: 12,
    winnerTo: 20,
    source: {
      winnerSources: [],
      loserSources: [7, 8],
    },
  },
  {
    name: "Winners Quarter-Finals",
    wBracket: true,
    lBracket: false,
    round: 2,
    id: 13,
    winnerTo: 21,
    loserTo: 20,
    source: {
      winnerSources: [1, 2],
      loserSources: [],
    },
  },
  {
    name: "Winners Quarter-Finals",
    wBracket: true,
    lBracket: false,
    round: 2,
    id: 14,
    winnerTo: 21,
    loserTo: 19,
    source: {
      winnerSources: [3, 4],
      loserSources: [],
    },
  },
  {
    name: "Winners Quarter-Finals",
    wBracket: true,
    lBracket: false,
    round: 2,
    id: 15,
    winnerTo: 22,
    loserTo: 18,
    source: {
      winnerSources: [5, 6],
      loserSources: [],
    },
  },
  {
    name: "Winners Quarter-Finals",
    wBracket: true,
    lBracket: false,
    round: 2,
    id: 16,
    winnerTo: 22,
    loserTo: 17,
    source: {
      winnerSources: [7, 8],
      loserSources: [],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 2,
    id: 17,
    winnerTo: 23,
    source: {
      winnerSources: [9],
      loserSources: [16],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 2,
    id: 18,
    winnerTo: 23,
    source: {
      winnerSources: [10],
      loserSources: [15],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 2,
    id: 19,
    winnerTo: 24,
    source: {
      winnerSources: [11],
      loserSources: [14],
    },
  },
  {
    name: "Losers Quarter-Finals",
    wBracket: false,
    lBracket: true,
    round: 2,
    id: 20,
    winnerTo: 24,
    source: {
      winnerSources: [12],
      loserSources: [13],
    },
  },
  {
    name: "Winners Semi-Finals",
    wBracket: true,
    lBracket: false,
    round: 3,
    id: 21,
    winnerTo: 25,
    loserTo: 28,
    source: {
      winnerSources: [13, 14],
      loserSources: [],
    },
  },
  {
    name: "Winners Semi-Finals",
    wBracket: true,
    lBracket: false,
    round: 3,
    id: 22,
    winnerTo: 25,
    loserTo: 27,
    source: {
      winnerSources: [15, 16],
      loserSources: [],
    },
  },
  {
    name: "Losers Semi-Finals",
    wBracket: false,
    lBracket: true,
    round: 3,
    id: 23,
    winnerTo: 26,
    source: {
      winnerSources: [17, 18],
      loserSources: [],
    },
  },
  {
    name: "Losers Semi-Finals",
    wBracket: false,
    lBracket: true,
    round: 3,
    id: 24,
    winnerTo: 27,
    source: {
      winnerSources: [19, 20],
      loserSources: [],
    },
  },
  {
    name: "winner finals",
    wBracket: true,
    lBracket: false,
    round: 4,
    id: 25,
    winnerTo: 30,
    loserTo: 29,
    source: {
      winnerSources: [21, 22],
      loserSources: [],
    },
  },
  {
    name: "Losers Semi-Finals",
    wBracket: false,
    lBracket: true,
    round: 4,
    id: 26,
    winnerTo: 29,
    source: {
      winnerSources: [23],
      loserSources: [],
    },
  },
  {
    name: "Losers Semi-Finals",
    wBracket: false,
    lBracket: true,
    round: 4,
    id: 27,
    winnerTo: 29,
    source: {
      winnerSources: [24],
      loserSources: [22],
    },
  },
  {
    name: "Losers Finals",
    wBracket: false,
    lBracket: true,
    round: 5,
    id: 28,
    winnerTo: 29,
    source: {
      winnerSources: [],
      loserSources: [21],
    },
  },
  {
    name: "Losers Finals",
    wBracket: false,
    lBracket: true,
    round: 6,
    id: 29,
    winnerTo: 30,
    source: {
      winnerSources: [26, 27, 28],
      loserSources: [25],
    },
  },
  {
    name: "Grand Finals",
    id: 30,
  },
  {
    name: "Grand Finals",
    id: 31,
  },
];
