<<<<<<< HEAD
export const testqual = [
  {
    id: 1,
    eventId: 1,
    playerId: 278,
    score: 944269,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 2,
    eventId: 1,
    playerId: 414,
    score: 948920,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 3,
    eventId: 1,
    playerId: 493,
    score: 989680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 4,
    eventId: 1,
    playerId: 769,
    score: 973493,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 5,
    eventId: 1,
    playerId: 1025,
    score: 997420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 6,
    eventId: 1,
    playerId: 691,
    score: 987700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 7,
    eventId: 1,
    playerId: 69,
    score: 964580,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 8,
    eventId: 1,
    playerId: 306,
    score: 996520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 9,
    eventId: 1,
    playerId: 928,
    score: 985340,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 10,
    eventId: 1,
    playerId: 582,
    score: 999460,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 11,
    eventId: 1,
    playerId: 336,
    score: 756440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 12,
    eventId: 1,
    playerId: 780,
    score: 991980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 13,
    eventId: 1,
    playerId: 93,
    score: 963980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 14,
    eventId: 1,
    playerId: 525,
    score: 955400,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 15,
    eventId: 1,
    playerId: 681,
    score: 990700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 16,
    eventId: 1,
    playerId: 473,
    score: 981420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 17,
    eventId: 1,
    playerId: 161,
    score: 999540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 18,
    eventId: 1,
    playerId: 908,
    score: 964081,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 19,
    eventId: 1,
    playerId: 660,
    score: 973260,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 20,
    eventId: 1,
    playerId: 307,
    score: 973060,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 21,
    eventId: 1,
    playerId: 520,
    score: 997360,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 22,
    eventId: 1,
    playerId: 378,
    score: 941101,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 23,
    eventId: 1,
    playerId: 818,
    score: 874640,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 24,
    eventId: 1,
    playerId: 279,
    score: 950980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 25,
    eventId: 1,
    playerId: 871,
    score: 934120,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 26,
    eventId: 1,
    playerId: 697,
    score: 997420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 27,
    eventId: 1,
    playerId: 219,
    score: 963520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 28,
    eventId: 1,
    playerId: 628,
    score: 958640,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 29,
    eventId: 1,
    playerId: 694,
    score: 995412,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 30,
    eventId: 1,
    playerId: 705,
    score: 885780,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 31,
    eventId: 1,
    playerId: 1089,
    score: 976842,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 32,
    eventId: 1,
    playerId: 1032,
    score: 917708,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 33,
    eventId: 1,
    playerId: 80,
    score: 907960,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 34,
    eventId: 1,
    playerId: 567,
    score: 983567,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 35,
    eventId: 1,
    playerId: 1109,
    score: 944440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 36,
    eventId: 1,
    playerId: 803,
    score: 975579,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 37,
    eventId: 1,
    playerId: 1108,
    score: 979516,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 38,
    eventId: 1,
    playerId: 1105,
    score: 994409,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 39,
    eventId: 1,
    playerId: 1059,
    score: 877160,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 40,
    eventId: 1,
    playerId: 739,
    score: 873200,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 41,
    eventId: 1,
    playerId: 55,
    score: 993054,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 42,
    eventId: 1,
    playerId: 403,
    score: 881120,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 43,
    eventId: 1,
    playerId: 298,
    score: 966540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 44,
    eventId: 1,
    playerId: 616,
    score: 975251,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 45,
    eventId: 1,
    playerId: 762,
    score: 970680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 46,
    eventId: 1,
    playerId: 621,
    score: 966418,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 47,
    eventId: 1,
    playerId: 954,
    score: 945220,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 48,
    eventId: 1,
    playerId: 1095,
    score: 932180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 49,
    eventId: 1,
    playerId: 257,
    score: 985072,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 50,
    eventId: 1,
    playerId: 882,
    score: 894320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 51,
    eventId: 1,
    playerId: 276,
    score: 770540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 52,
    eventId: 1,
    playerId: 666,
    score: 959680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 53,
    eventId: 1,
    playerId: 900,
    score: 984175,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 54,
    eventId: 1,
    playerId: 711,
    score: 961760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 55,
    eventId: 1,
    playerId: 710,
    score: 834520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 56,
    eventId: 1,
    playerId: 1106,
    score: 868232,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 57,
    eventId: 1,
    playerId: 761,
    score: 834660,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 58,
    eventId: 1,
    playerId: 404,
    score: 924985,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 59,
    eventId: 1,
    playerId: 934,
    score: 901309,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 60,
    eventId: 1,
    playerId: 477,
    score: 881700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 61,
    eventId: 1,
    playerId: 1001,
    score: 906760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 62,
    eventId: 1,
    playerId: 4,
    score: 917660,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 63,
    eventId: 1,
    playerId: 724,
    score: 859760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 64,
    eventId: 1,
    playerId: 406,
    score: 856846,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 65,
    eventId: 1,
    playerId: 395,
    score: 908440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 66,
    eventId: 1,
    playerId: 820,
    score: 837563,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 67,
    eventId: 1,
    playerId: 104,
    score: 939860,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 68,
    eventId: 1,
    playerId: 451,
    score: 944620,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 69,
    eventId: 1,
    playerId: 635,
    score: 837700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 70,
    eventId: 1,
    playerId: 970,
    score: 942420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 71,
    eventId: 1,
    playerId: 367,
    score: 950432,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 72,
    eventId: 1,
    playerId: 74,
    score: 866180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 73,
    eventId: 1,
    playerId: 97,
    score: 832488,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 74,
    eventId: 1,
    playerId: 630,
    score: 825060,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 75,
    eventId: 1,
    playerId: 421,
    score: 823720,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 76,
    eventId: 1,
    playerId: 1085,
    score: 819476,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 77,
    eventId: 1,
    playerId: 462,
    score: 814190,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 78,
    eventId: 1,
    playerId: 1040,
    score: 812560,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 79,
    eventId: 1,
    playerId: 359,
    score: 809010,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 80,
    eventId: 1,
    playerId: 482,
    score: 807900,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 81,
    eventId: 1,
    playerId: 124,
    score: 801540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 82,
    eventId: 1,
    playerId: 299,
    score: 792400,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 83,
    eventId: 1,
    playerId: 386,
    score: 777320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 84,
    eventId: 1,
    playerId: 731,
    score: 771932,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 85,
    eventId: 1,
    playerId: 743,
    score: 771528,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 86,
    eventId: 1,
    playerId: 1058,
    score: 752751,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 87,
    eventId: 1,
    playerId: 369,
    score: 747969,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 88,
    eventId: 1,
    playerId: 783,
    score: 730533,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 89,
    eventId: 1,
    playerId: 637,
    score: 718333,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 90,
    eventId: 1,
    playerId: 399,
    score: 709140,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 91,
    eventId: 1,
    playerId: 484,
    score: 708980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 92,
    eventId: 1,
    playerId: 721,
    score: 693240,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 93,
    eventId: 1,
    playerId: 447,
    score: 655276,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 94,
    eventId: 1,
    playerId: 54,
    score: 651512,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 95,
    eventId: 1,
    playerId: 767,
    score: 642898,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 96,
    eventId: 1,
    playerId: 1270,
    score: 621389,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 97,
    eventId: 1,
    playerId: 269,
    score: 555180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 98,
    eventId: 1,
    playerId: 1092,
    score: 517320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 99,
    eventId: 1,
    playerId: 455,
    score: 493300,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 100,
    eventId: 1,
    playerId: 913,
    score: 443184,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 101,
    eventId: 1,
    playerId: 59,
    score: 359820,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 102,
    eventId: 1,
    playerId: 1134,
    score: 301905,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
];
=======
export const testqual = [
  {
    id: 1,
    eventId: 1,
    playerId: 278,
    score: 944269,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 2,
    eventId: 1,
    playerId: 414,
    score: 948920,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 3,
    eventId: 1,
    playerId: 493,
    score: 989680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 4,
    eventId: 1,
    playerId: 769,
    score: 973493,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 5,
    eventId: 1,
    playerId: 1025,
    score: 997420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 6,
    eventId: 1,
    playerId: 691,
    score: 987700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 7,
    eventId: 1,
    playerId: 69,
    score: 964580,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 8,
    eventId: 1,
    playerId: 306,
    score: 996520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 9,
    eventId: 1,
    playerId: 928,
    score: 985340,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 10,
    eventId: 1,
    playerId: 582,
    score: 999460,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 11,
    eventId: 1,
    playerId: 336,
    score: 756440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 12,
    eventId: 1,
    playerId: 780,
    score: 991980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 13,
    eventId: 1,
    playerId: 93,
    score: 963980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 14,
    eventId: 1,
    playerId: 525,
    score: 955400,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 15,
    eventId: 1,
    playerId: 681,
    score: 990700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 16,
    eventId: 1,
    playerId: 473,
    score: 981420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 17,
    eventId: 1,
    playerId: 161,
    score: 999540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 18,
    eventId: 1,
    playerId: 908,
    score: 964081,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 19,
    eventId: 1,
    playerId: 660,
    score: 973260,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 20,
    eventId: 1,
    playerId: 307,
    score: 973060,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 21,
    eventId: 1,
    playerId: 520,
    score: 997360,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 22,
    eventId: 1,
    playerId: 378,
    score: 941101,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 23,
    eventId: 1,
    playerId: 818,
    score: 874640,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 24,
    eventId: 1,
    playerId: 279,
    score: 950980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 25,
    eventId: 1,
    playerId: 871,
    score: 934120,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 26,
    eventId: 1,
    playerId: 697,
    score: 997420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 27,
    eventId: 1,
    playerId: 219,
    score: 963520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 28,
    eventId: 1,
    playerId: 628,
    score: 958640,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 29,
    eventId: 1,
    playerId: 694,
    score: 995412,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 30,
    eventId: 1,
    playerId: 705,
    score: 885780,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 31,
    eventId: 1,
    playerId: 1089,
    score: 976842,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 32,
    eventId: 1,
    playerId: 1032,
    score: 917708,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 33,
    eventId: 1,
    playerId: 80,
    score: 907960,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 34,
    eventId: 1,
    playerId: 567,
    score: 983567,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 35,
    eventId: 1,
    playerId: 1109,
    score: 944440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 36,
    eventId: 1,
    playerId: 803,
    score: 975579,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 37,
    eventId: 1,
    playerId: 1108,
    score: 979516,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 38,
    eventId: 1,
    playerId: 1105,
    score: 994409,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 39,
    eventId: 1,
    playerId: 1059,
    score: 877160,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 40,
    eventId: 1,
    playerId: 739,
    score: 873200,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 41,
    eventId: 1,
    playerId: 55,
    score: 993054,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 42,
    eventId: 1,
    playerId: 403,
    score: 881120,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 43,
    eventId: 1,
    playerId: 298,
    score: 966540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 44,
    eventId: 1,
    playerId: 616,
    score: 975251,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 45,
    eventId: 1,
    playerId: 762,
    score: 970680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 46,
    eventId: 1,
    playerId: 621,
    score: 966418,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 47,
    eventId: 1,
    playerId: 954,
    score: 945220,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 48,
    eventId: 1,
    playerId: 1095,
    score: 932180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 49,
    eventId: 1,
    playerId: 257,
    score: 985072,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 50,
    eventId: 1,
    playerId: 882,
    score: 894320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 51,
    eventId: 1,
    playerId: 276,
    score: 770540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 52,
    eventId: 1,
    playerId: 666,
    score: 959680,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 53,
    eventId: 1,
    playerId: 900,
    score: 984175,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 54,
    eventId: 1,
    playerId: 711,
    score: 961760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 55,
    eventId: 1,
    playerId: 710,
    score: 834520,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 56,
    eventId: 1,
    playerId: 1106,
    score: 868232,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 57,
    eventId: 1,
    playerId: 761,
    score: 834660,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 58,
    eventId: 1,
    playerId: 404,
    score: 924985,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 59,
    eventId: 1,
    playerId: 934,
    score: 901309,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 60,
    eventId: 1,
    playerId: 477,
    score: 881700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 61,
    eventId: 1,
    playerId: 1001,
    score: 906760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 62,
    eventId: 1,
    playerId: 4,
    score: 917660,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 63,
    eventId: 1,
    playerId: 724,
    score: 859760,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 64,
    eventId: 1,
    playerId: 406,
    score: 856846,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 65,
    eventId: 1,
    playerId: 395,
    score: 908440,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 66,
    eventId: 1,
    playerId: 820,
    score: 837563,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 67,
    eventId: 1,
    playerId: 104,
    score: 939860,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 68,
    eventId: 1,
    playerId: 451,
    score: 944620,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 69,
    eventId: 1,
    playerId: 635,
    score: 837700,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 70,
    eventId: 1,
    playerId: 970,
    score: 942420,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 71,
    eventId: 1,
    playerId: 367,
    score: 950432,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 72,
    eventId: 1,
    playerId: 74,
    score: 866180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 73,
    eventId: 1,
    playerId: 97,
    score: 832488,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 74,
    eventId: 1,
    playerId: 630,
    score: 825060,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 75,
    eventId: 1,
    playerId: 421,
    score: 823720,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 76,
    eventId: 1,
    playerId: 1085,
    score: 819476,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 77,
    eventId: 1,
    playerId: 462,
    score: 814190,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 78,
    eventId: 1,
    playerId: 1040,
    score: 812560,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 79,
    eventId: 1,
    playerId: 359,
    score: 809010,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 80,
    eventId: 1,
    playerId: 482,
    score: 807900,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 81,
    eventId: 1,
    playerId: 124,
    score: 801540,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 82,
    eventId: 1,
    playerId: 299,
    score: 792400,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 83,
    eventId: 1,
    playerId: 386,
    score: 777320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 84,
    eventId: 1,
    playerId: 731,
    score: 771932,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 85,
    eventId: 1,
    playerId: 743,
    score: 771528,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 86,
    eventId: 1,
    playerId: 1058,
    score: 752751,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 87,
    eventId: 1,
    playerId: 369,
    score: 747969,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 88,
    eventId: 1,
    playerId: 783,
    score: 730533,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 89,
    eventId: 1,
    playerId: 637,
    score: 718333,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 90,
    eventId: 1,
    playerId: 399,
    score: 709140,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 91,
    eventId: 1,
    playerId: 484,
    score: 708980,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 92,
    eventId: 1,
    playerId: 721,
    score: 693240,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 93,
    eventId: 1,
    playerId: 447,
    score: 655276,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 94,
    eventId: 1,
    playerId: 54,
    score: 651512,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 95,
    eventId: 1,
    playerId: 767,
    score: 642898,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 96,
    eventId: 1,
    playerId: 1270,
    score: 621389,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 97,
    eventId: 1,
    playerId: 269,
    score: 555180,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 98,
    eventId: 1,
    playerId: 1092,
    score: 517320,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 99,
    eventId: 1,
    playerId: 455,
    score: 493300,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 100,
    eventId: 1,
    playerId: 913,
    score: 443184,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 101,
    eventId: 1,
    playerId: 59,
    score: 359820,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
  {
    id: 102,
    eventId: 1,
    playerId: 1134,
    score: 301905,
    pending: true,
    approved: false,
    timestamp: null,
    videoLink: null,
  },
];
>>>>>>> d251a519147c0ccd9a5e691845043e3883ceda8b
