export const countryList = [
  {
    Country: "Afghanistan",
    Code2: "AF",
    Code3: "AFG",
    Numeric: 4,
  },
  {
    Country: "Albania",
    Code2: "AL",
    Code3: "ALB",
    Numeric: 8,
  },
  {
    Country: "Algeria",
    Code2: "DZ",
    Code3: "DZA",
    Numeric: 12,
  },
  {
    Country: "American Samoa",
    Code2: "AS",
    Code3: "ASM",
    Numeric: 16,
  },
  {
    Country: "Andorra",
    Code2: "AD",
    Code3: "AND",
    Numeric: 20,
  },
  {
    Country: "Angola",
    Code2: "AO",
    Code3: "AGO",
    Numeric: 24,
  },
  {
    Country: "Anguilla",
    Code2: "AI",
    Code3: "AIA",
    Numeric: 660,
  },
  {
    Country: "Antarctica",
    Code2: "AQ",
    Code3: "ATA",
    Numeric: 10,
  },
  {
    Country: "Antigua and Barbuda",
    Code2: "AG",
    Code3: "ATG",
    Numeric: 28,
  },
  {
    Country: "Argentina",
    Code2: "AR",
    Code3: "ARG",
    Numeric: 32,
  },
  {
    Country: "Armenia",
    Code2: "AM",
    Code3: "ARM",
    Numeric: 51,
  },
  {
    Country: "Aruba",
    Code2: "AW",
    Code3: "ABW",
    Numeric: 533,
  },
  {
    Country: "Australia",
    Code2: "AU",
    Code3: "AUS",
    Numeric: 36,
  },
  {
    Country: "Austria",
    Code2: "AT",
    Code3: "AUT",
    Numeric: 40,
  },
  {
    Country: "Azerbaijan",
    Code2: "AZ",
    Code3: "AZE",
    Numeric: 31,
  },
  {
    Country: "Bahamas (the)",
    Code2: "BS",
    Code3: "BHS",
    Numeric: 44,
  },
  {
    Country: "Bahrain",
    Code2: "BH",
    Code3: "BHR",
    Numeric: 48,
  },
  {
    Country: "Bangladesh",
    Code2: "BD",
    Code3: "BGD",
    Numeric: 50,
  },
  {
    Country: "Barbados",
    Code2: "BB",
    Code3: "BRB",
    Numeric: 52,
  },
  {
    Country: "Belarus",
    Code2: "BY",
    Code3: "BLR",
    Numeric: 112,
  },
  {
    Country: "Belgium",
    Code2: "BE",
    Code3: "BEL",
    Numeric: 56,
  },
  {
    Country: "Belize",
    Code2: "BZ",
    Code3: "BLZ",
    Numeric: 84,
  },
  {
    Country: "Benin",
    Code2: "BJ",
    Code3: "BEN",
    Numeric: 204,
  },
  {
    Country: "Bermuda",
    Code2: "BM",
    Code3: "BMU",
    Numeric: 60,
  },
  {
    Country: "Bhutan",
    Code2: "BT",
    Code3: "BTN",
    Numeric: 64,
  },
  {
    Country: "Bolivia (Plurinational State of)",
    Code2: "BO",
    Code3: "BOL",
    Numeric: 68,
  },
  {
    Country: "Bonaire, Sint Eustatius and Saba",
    Code2: "BQ",
    Code3: "BES",
    Numeric: 535,
  },
  {
    Country: "Bosnia and Herzegovina",
    Code2: "BA",
    Code3: "BIH",
    Numeric: 70,
  },
  {
    Country: "Botswana",
    Code2: "BW",
    Code3: "BWA",
    Numeric: 72,
  },
  {
    Country: "Bouvet Island",
    Code2: "BV",
    Code3: "BVT",
    Numeric: 74,
  },
  {
    Country: "Brazil",
    Code2: "BR",
    Code3: "BRA",
    Numeric: 76,
  },
  {
    Country: "British Indian Ocean Territory (the)",
    Code2: "IO",
    Code3: "IOT",
    Numeric: 86,
  },
  {
    Country: "Brunei Darussalam",
    Code2: "BN",
    Code3: "BRN",
    Numeric: 96,
  },
  {
    Country: "Bulgaria",
    Code2: "BG",
    Code3: "BGR",
    Numeric: 100,
  },
  {
    Country: "Burkina Faso",
    Code2: "BF",
    Code3: "BFA",
    Numeric: 854,
  },
  {
    Country: "Burundi",
    Code2: "BI",
    Code3: "BDI",
    Numeric: 108,
  },
  {
    Country: "Cabo Verde",
    Code2: "CV",
    Code3: "CPV",
    Numeric: 132,
  },
  {
    Country: "Cambodia",
    Code2: "KH",
    Code3: "KHM",
    Numeric: 116,
  },
  {
    Country: "Cameroon",
    Code2: "CM",
    Code3: "CMR",
    Numeric: 120,
  },
  {
    Country: "Canada",
    Code2: "CA",
    Code3: "CAN",
    Numeric: 124,
  },
  {
    Country: "Cayman Islands (the)",
    Code2: "KY",
    Code3: "CYM",
    Numeric: 136,
  },
  {
    Country: "Central African Republic (the)",
    Code2: "CF",
    Code3: "CAF",
    Numeric: 140,
  },
  {
    Country: "Chad",
    Code2: "TD",
    Code3: "TCD",
    Numeric: 148,
  },
  {
    Country: "Chile",
    Code2: "CL",
    Code3: "CHL",
    Numeric: 152,
  },
  {
    Country: "China",
    Code2: "CN",
    Code3: "CHN",
    Numeric: 156,
  },
  {
    Country: "Christmas Island",
    Code2: "CX",
    Code3: "CXR",
    Numeric: 162,
  },
  {
    Country: "Cocos (Keeling) Islands (the)",
    Code2: "CC",
    Code3: "CCK",
    Numeric: 166,
  },
  {
    Country: "Colombia",
    Code2: "CO",
    Code3: "COL",
    Numeric: 170,
  },
  {
    Country: "Comoros (the)",
    Code2: "KM",
    Code3: "COM",
    Numeric: 174,
  },
  {
    Country: "Congo (the Democratic Republic of the)",
    Code2: "CD",
    Code3: "COD",
    Numeric: 180,
  },
  {
    Country: "Congo (the)",
    Code2: "CG",
    Code3: "COG",
    Numeric: 178,
  },
  {
    Country: "Cook Islands (the)",
    Code2: "CK",
    Code3: "COK",
    Numeric: 184,
  },
  {
    Country: "Costa Rica",
    Code2: "CR",
    Code3: "CRI",
    Numeric: 188,
  },
  {
    Country: "Croatia",
    Code2: "HR",
    Code3: "HRV",
    Numeric: 191,
  },
  {
    Country: "Cuba",
    Code2: "CU",
    Code3: "CUB",
    Numeric: 192,
  },
  {
    Country: "Curaçao",
    Code2: "CW",
    Code3: "CUW",
    Numeric: 531,
  },
  {
    Country: "Cyprus",
    Code2: "CY",
    Code3: "CYP",
    Numeric: 196,
  },
  {
    Country: "Czechia",
    Code2: "CZ",
    Code3: "CZE",
    Numeric: 203,
  },
  {
    Country: "Côte d'Ivoire",
    Code2: "CI",
    Code3: "CIV",
    Numeric: 384,
  },
  {
    Country: "Denmark",
    Code2: "DK",
    Code3: "DNK",
    Numeric: 208,
  },
  {
    Country: "Djibouti",
    Code2: "DJ",
    Code3: "DJI",
    Numeric: 262,
  },
  {
    Country: "Dominica",
    Code2: "DM",
    Code3: "DMA",
    Numeric: 212,
  },
  {
    Country: "Dominican Republic (the)",
    Code2: "DO",
    Code3: "DOM",
    Numeric: 214,
  },
  {
    Country: "Ecuador",
    Code2: "EC",
    Code3: "ECU",
    Numeric: 218,
  },
  {
    Country: "Egypt",
    Code2: "EG",
    Code3: "EGY",
    Numeric: 818,
  },
  {
    Country: "El Salvador",
    Code2: "SV",
    Code3: "SLV",
    Numeric: 222,
  },
  {
    Country: "Equatorial Guinea",
    Code2: "GQ",
    Code3: "GNQ",
    Numeric: 226,
  },
  {
    Country: "Eritrea",
    Code2: "ER",
    Code3: "ERI",
    Numeric: 232,
  },
  {
    Country: "Estonia",
    Code2: "EE",
    Code3: "EST",
    Numeric: 233,
  },
  {
    Country: "Eswatini",
    Code2: "SZ",
    Code3: "SWZ",
    Numeric: 748,
  },
  {
    Country: "Ethiopia",
    Code2: "ET",
    Code3: "ETH",
    Numeric: 231,
  },
  {
    Country: "Falkland Islands (the) [Malvinas]",
    Code2: "FK",
    Code3: "FLK",
    Numeric: 238,
  },
  {
    Country: "Faroe Islands (the)",
    Code2: "FO",
    Code3: "FRO",
    Numeric: 234,
  },
  {
    Country: "Fiji",
    Code2: "FJ",
    Code3: "FJI",
    Numeric: 242,
  },
  {
    Country: "Finland",
    Code2: "FI",
    Code3: "FIN",
    Numeric: 246,
  },
  {
    Country: "France",
    Code2: "FR",
    Code3: "FRA",
    Numeric: 250,
  },
  {
    Country: "French Guiana",
    Code2: "GF",
    Code3: "GUF",
    Numeric: 254,
  },
  {
    Country: "French Polynesia",
    Code2: "PF",
    Code3: "PYF",
    Numeric: 258,
  },
  {
    Country: "French Southern Territories (the)",
    Code2: "TF",
    Code3: "ATF",
    Numeric: 260,
  },
  {
    Country: "Gabon",
    Code2: "GA",
    Code3: "GAB",
    Numeric: 266,
  },
  {
    Country: "Gambia (the)",
    Code2: "GM",
    Code3: "GMB",
    Numeric: 270,
  },
  {
    Country: "Georgia",
    Code2: "GE",
    Code3: "GEO",
    Numeric: 268,
  },
  {
    Country: "Germany",
    Code2: "DE",
    Code3: "DEU",
    Numeric: 276,
  },
  {
    Country: "Ghana",
    Code2: "GH",
    Code3: "GHA",
    Numeric: 288,
  },
  {
    Country: "Gibraltar",
    Code2: "GI",
    Code3: "GIB",
    Numeric: 292,
  },
  {
    Country: "Greece",
    Code2: "GR",
    Code3: "GRC",
    Numeric: 300,
  },
  {
    Country: "Greenland",
    Code2: "GL",
    Code3: "GRL",
    Numeric: 304,
  },
  {
    Country: "Grenada",
    Code2: "GD",
    Code3: "GRD",
    Numeric: 308,
  },
  {
    Country: "Guadeloupe",
    Code2: "GP",
    Code3: "GLP",
    Numeric: 312,
  },
  {
    Country: "Guam",
    Code2: "GU",
    Code3: "GUM",
    Numeric: 316,
  },
  {
    Country: "Guatemala",
    Code2: "GT",
    Code3: "GTM",
    Numeric: 320,
  },
  {
    Country: "Guernsey",
    Code2: "GG",
    Code3: "GGY",
    Numeric: 831,
  },
  {
    Country: "Guinea",
    Code2: "GN",
    Code3: "GIN",
    Numeric: 324,
  },
  {
    Country: "Guinea-Bissau",
    Code2: "GW",
    Code3: "GNB",
    Numeric: 624,
  },
  {
    Country: "Guyana",
    Code2: "GY",
    Code3: "GUY",
    Numeric: 328,
  },
  {
    Country: "Haiti",
    Code2: "HT",
    Code3: "HTI",
    Numeric: 332,
  },
  {
    Country: "Heard Island and McDonald Islands",
    Code2: "HM",
    Code3: "HMD",
    Numeric: 334,
  },
  {
    Country: "Holy See (the)",
    Code2: "VA",
    Code3: "VAT",
    Numeric: 336,
  },
  {
    Country: "Honduras",
    Code2: "HN",
    Code3: "HND",
    Numeric: 340,
  },
  {
    Country: "Hong Kong",
    Code2: "HK",
    Code3: "HKG",
    Numeric: 344,
  },
  {
    Country: "Hungary",
    Code2: "HU",
    Code3: "HUN",
    Numeric: 348,
  },
  {
    Country: "Iceland",
    Code2: "IS",
    Code3: "ISL",
    Numeric: 352,
  },
  {
    Country: "India",
    Code2: "IN",
    Code3: "IND",
    Numeric: 356,
  },
  {
    Country: "Indonesia",
    Code2: "ID",
    Code3: "IDN",
    Numeric: 360,
  },
  {
    Country: "Iran (Islamic Republic of)",
    Code2: "IR",
    Code3: "IRN",
    Numeric: 364,
  },
  {
    Country: "Iraq",
    Code2: "IQ",
    Code3: "IRQ",
    Numeric: 368,
  },
  {
    Country: "Ireland",
    Code2: "IE",
    Code3: "IRL",
    Numeric: 372,
  },
  {
    Country: "Isle of Man",
    Code2: "IM",
    Code3: "IMN",
    Numeric: 833,
  },
  {
    Country: "Israel",
    Code2: "IL",
    Code3: "ISR",
    Numeric: 376,
  },
  {
    Country: "Italy",
    Code2: "IT",
    Code3: "ITA",
    Numeric: 380,
  },
  {
    Country: "Jamaica",
    Code2: "JM",
    Code3: "JAM",
    Numeric: 388,
  },
  {
    Country: "Japan",
    Code2: "JP",
    Code3: "JPN",
    Numeric: 392,
  },
  {
    Country: "Jersey",
    Code2: "JE",
    Code3: "JEY",
    Numeric: 832,
  },
  {
    Country: "Jordan",
    Code2: "JO",
    Code3: "JOR",
    Numeric: 400,
  },
  {
    Country: "Kazakhstan",
    Code2: "KZ",
    Code3: "KAZ",
    Numeric: 398,
  },
  {
    Country: "Kenya",
    Code2: "KE",
    Code3: "KEN",
    Numeric: 404,
  },
  {
    Country: "Kiribati",
    Code2: "KI",
    Code3: "KIR",
    Numeric: 296,
  },
  {
    Country: "Korea (the Democratic People's Republic of)",
    Code2: "KP",
    Code3: "PRK",
    Numeric: 408,
  },
  {
    Country: "Korea (the Republic of)",
    Code2: "KR",
    Code3: "KOR",
    Numeric: 410,
  },
  {
    Country: "Kuwait",
    Code2: "KW",
    Code3: "KWT",
    Numeric: 414,
  },
  {
    Country: "Kyrgyzstan",
    Code2: "KG",
    Code3: "KGZ",
    Numeric: 417,
  },
  {
    Country: "Lao People's Democratic Republic (the)",
    Code2: "LA",
    Code3: "LAO",
    Numeric: 418,
  },
  {
    Country: "Latvia",
    Code2: "LV",
    Code3: "LVA",
    Numeric: 428,
  },
  {
    Country: "Lebanon",
    Code2: "LB",
    Code3: "LBN",
    Numeric: 422,
  },
  {
    Country: "Lesotho",
    Code2: "LS",
    Code3: "LSO",
    Numeric: 426,
  },
  {
    Country: "Liberia",
    Code2: "LR",
    Code3: "LBR",
    Numeric: 430,
  },
  {
    Country: "Libya",
    Code2: "LY",
    Code3: "LBY",
    Numeric: 434,
  },
  {
    Country: "Liechtenstein",
    Code2: "LI",
    Code3: "LIE",
    Numeric: 438,
  },
  {
    Country: "Lithuania",
    Code2: "LT",
    Code3: "LTU",
    Numeric: 440,
  },
  {
    Country: "Luxembourg",
    Code2: "LU",
    Code3: "LUX",
    Numeric: 442,
  },
  {
    Country: "Macao",
    Code2: "MO",
    Code3: "MAC",
    Numeric: 446,
  },
  {
    Country: "Madagascar",
    Code2: "MG",
    Code3: "MDG",
    Numeric: 450,
  },
  {
    Country: "Malawi",
    Code2: "MW",
    Code3: "MWI",
    Numeric: 454,
  },
  {
    Country: "Malaysia",
    Code2: "MY",
    Code3: "MYS",
    Numeric: 458,
  },
  {
    Country: "Maldives",
    Code2: "MV",
    Code3: "MDV",
    Numeric: 462,
  },
  {
    Country: "Mali",
    Code2: "ML",
    Code3: "MLI",
    Numeric: 466,
  },
  {
    Country: "Malta",
    Code2: "MT",
    Code3: "MLT",
    Numeric: 470,
  },
  {
    Country: "Marshall Islands (the)",
    Code2: "MH",
    Code3: "MHL",
    Numeric: 584,
  },
  {
    Country: "Martinique",
    Code2: "MQ",
    Code3: "MTQ",
    Numeric: 474,
  },
  {
    Country: "Mauritania",
    Code2: "MR",
    Code3: "MRT",
    Numeric: 478,
  },
  {
    Country: "Mauritius",
    Code2: "MU",
    Code3: "MUS",
    Numeric: 480,
  },
  {
    Country: "Mayotte",
    Code2: "YT",
    Code3: "MYT",
    Numeric: 175,
  },
  {
    Country: "Mexico",
    Code2: "MX",
    Code3: "MEX",
    Numeric: 484,
  },
  {
    Country: "Micronesia (Federated States of)",
    Code2: "FM",
    Code3: "FSM",
    Numeric: 583,
  },
  {
    Country: "Moldova (the Republic of)",
    Code2: "MD",
    Code3: "MDA",
    Numeric: 498,
  },
  {
    Country: "Monaco",
    Code2: "MC",
    Code3: "MCO",
    Numeric: 492,
  },
  {
    Country: "Mongolia",
    Code2: "MN",
    Code3: "MNG",
    Numeric: 496,
  },
  {
    Country: "Montenegro",
    Code2: "ME",
    Code3: "MNE",
    Numeric: 499,
  },
  {
    Country: "Montserrat",
    Code2: "MS",
    Code3: "MSR",
    Numeric: 500,
  },
  {
    Country: "Morocco",
    Code2: "MA",
    Code3: "MAR",
    Numeric: 504,
  },
  {
    Country: "Mozambique",
    Code2: "MZ",
    Code3: "MOZ",
    Numeric: 508,
  },
  {
    Country: "Myanmar",
    Code2: "MM",
    Code3: "MMR",
    Numeric: 104,
  },
  {
    Country: "Namibia",
    Code2: "NA",
    Code3: "NAM",
    Numeric: 516,
  },
  {
    Country: "Nauru",
    Code2: "NR",
    Code3: "NRU",
    Numeric: 520,
  },
  {
    Country: "Nepal",
    Code2: "NP",
    Code3: "NPL",
    Numeric: 524,
  },
  {
    Country: "Netherlands (the)",
    Code2: "NL",
    Code3: "NLD",
    Numeric: 528,
  },
  {
    Country: "New Caledonia",
    Code2: "NC",
    Code3: "NCL",
    Numeric: 540,
  },
  {
    Country: "New Zealand",
    Code2: "NZ",
    Code3: "NZL",
    Numeric: 554,
  },
  {
    Country: "Nicaragua",
    Code2: "NI",
    Code3: "NIC",
    Numeric: 558,
  },
  {
    Country: "Niger (the)",
    Code2: "NE",
    Code3: "NER",
    Numeric: 562,
  },
  {
    Country: "Nigeria",
    Code2: "NG",
    Code3: "NGA",
    Numeric: 566,
  },
  {
    Country: "Niue",
    Code2: "NU",
    Code3: "NIU",
    Numeric: 570,
  },
  {
    Country: "Norfolk Island",
    Code2: "NF",
    Code3: "NFK",
    Numeric: 574,
  },
  {
    Country: "Northern Mariana Islands (the)",
    Code2: "MP",
    Code3: "MNP",
    Numeric: 580,
  },
  {
    Country: "Norway",
    Code2: "NO",
    Code3: "NOR",
    Numeric: 578,
  },
  {
    Country: "Oman",
    Code2: "OM",
    Code3: "OMN",
    Numeric: 512,
  },
  {
    Country: "Pakistan",
    Code2: "PK",
    Code3: "PAK",
    Numeric: 586,
  },
  {
    Country: "Palau",
    Code2: "PW",
    Code3: "PLW",
    Numeric: 585,
  },
  {
    Country: "Palestine, State of",
    Code2: "PS",
    Code3: "PSE",
    Numeric: 275,
  },
  {
    Country: "Panama",
    Code2: "PA",
    Code3: "PAN",
    Numeric: 591,
  },
  {
    Country: "Papua New Guinea",
    Code2: "PG",
    Code3: "PNG",
    Numeric: 598,
  },
  {
    Country: "Paraguay",
    Code2: "PY",
    Code3: "PRY",
    Numeric: 600,
  },
  {
    Country: "Peru",
    Code2: "PE",
    Code3: "PER",
    Numeric: 604,
  },
  {
    Country: "Philippines (the)",
    Code2: "PH",
    Code3: "PHL",
    Numeric: 608,
  },
  {
    Country: "Pitcairn",
    Code2: "PN",
    Code3: "PCN",
    Numeric: 612,
  },
  {
    Country: "Poland",
    Code2: "PL",
    Code3: "POL",
    Numeric: 616,
  },
  {
    Country: "Portugal",
    Code2: "PT",
    Code3: "PRT",
    Numeric: 620,
  },
  {
    Country: "Puerto Rico",
    Code2: "PR",
    Code3: "PRI",
    Numeric: 630,
  },
  {
    Country: "Qatar",
    Code2: "QA",
    Code3: "QAT",
    Numeric: 634,
  },
  {
    Country: "Republic of North Macedonia",
    Code2: "MK",
    Code3: "MKD",
    Numeric: 807,
  },
  {
    Country: "Romania",
    Code2: "RO",
    Code3: "ROU",
    Numeric: 642,
  },
  {
    Country: "Russian Federation (the)",
    Code2: "RU",
    Code3: "RUS",
    Numeric: 643,
  },
  {
    Country: "Rwanda",
    Code2: "RW",
    Code3: "RWA",
    Numeric: 646,
  },
  {
    Country: "Réunion",
    Code2: "RE",
    Code3: "REU",
    Numeric: 638,
  },
  {
    Country: "Saint Barthélemy",
    Code2: "BL",
    Code3: "BLM",
    Numeric: 652,
  },
  {
    Country: "Saint Helena, Ascension and Tristan da Cunha",
    Code2: "SH",
    Code3: "SHN",
    Numeric: 654,
  },
  {
    Country: "Saint Kitts and Nevis",
    Code2: "KN",
    Code3: "KNA",
    Numeric: 659,
  },
  {
    Country: "Saint Lucia",
    Code2: "LC",
    Code3: "LCA",
    Numeric: 662,
  },
  {
    Country: "Saint Martin (French part)",
    Code2: "MF",
    Code3: "MAF",
    Numeric: 663,
  },
  {
    Country: "Saint Pierre and Miquelon",
    Code2: "PM",
    Code3: "SPM",
    Numeric: 666,
  },
  {
    Country: "Saint Vincent and the Grenadines",
    Code2: "VC",
    Code3: "VCT",
    Numeric: 670,
  },
  {
    Country: "Samoa",
    Code2: "WS",
    Code3: "WSM",
    Numeric: 882,
  },
  {
    Country: "San Marino",
    Code2: "SM",
    Code3: "SMR",
    Numeric: 674,
  },
  {
    Country: "Sao Tome and Principe",
    Code2: "ST",
    Code3: "STP",
    Numeric: 678,
  },
  {
    Country: "Saudi Arabia",
    Code2: "SA",
    Code3: "SAU",
    Numeric: 682,
  },
  {
    Country: "Senegal",
    Code2: "SN",
    Code3: "SEN",
    Numeric: 686,
  },
  {
    Country: "Serbia",
    Code2: "RS",
    Code3: "SRB",
    Numeric: 688,
  },
  {
    Country: "Seychelles",
    Code2: "SC",
    Code3: "SYC",
    Numeric: 690,
  },
  {
    Country: "Sierra Leone",
    Code2: "SL",
    Code3: "SLE",
    Numeric: 694,
  },
  {
    Country: "Singapore",
    Code2: "SG",
    Code3: "SGP",
    Numeric: 702,
  },
  {
    Country: "Sint Maarten (Dutch part)",
    Code2: "SX",
    Code3: "SXM",
    Numeric: 534,
  },
  {
    Country: "Slovakia",
    Code2: "SK",
    Code3: "SVK",
    Numeric: 703,
  },
  {
    Country: "Slovenia",
    Code2: "SI",
    Code3: "SVN",
    Numeric: 705,
  },
  {
    Country: "Solomon Islands",
    Code2: "SB",
    Code3: "SLB",
    Numeric: 90,
  },
  {
    Country: "Somalia",
    Code2: "SO",
    Code3: "SOM",
    Numeric: 706,
  },
  {
    Country: "South Africa",
    Code2: "ZA",
    Code3: "ZAF",
    Numeric: 710,
  },
  {
    Country: "South Georgia and the South Sandwich Islands",
    Code2: "GS",
    Code3: "SGS",
    Numeric: 239,
  },
  {
    Country: "South Sudan",
    Code2: "SS",
    Code3: "SSD",
    Numeric: 728,
  },
  {
    Country: "Spain",
    Code2: "ES",
    Code3: "ESP",
    Numeric: 724,
  },
  {
    Country: "Sri Lanka",
    Code2: "LK",
    Code3: "LKA",
    Numeric: 144,
  },
  {
    Country: "Sudan (the)",
    Code2: "SD",
    Code3: "SDN",
    Numeric: 729,
  },
  {
    Country: "Suriname",
    Code2: "SR",
    Code3: "SUR",
    Numeric: 740,
  },
  {
    Country: "Svalbard and Jan Mayen",
    Code2: "SJ",
    Code3: "SJM",
    Numeric: 744,
  },
  {
    Country: "Sweden",
    Code2: "SE",
    Code3: "SWE",
    Numeric: 752,
  },
  {
    Country: "Switzerland",
    Code2: "CH",
    Code3: "CHE",
    Numeric: 756,
  },
  {
    Country: "Syrian Arab Republic",
    Code2: "SY",
    Code3: "SYR",
    Numeric: 760,
  },
  {
    Country: "Taiwan (Province of China)",
    Code2: "TW",
    Code3: "TWN",
    Numeric: 158,
  },
  {
    Country: "Tajikistan",
    Code2: "TJ",
    Code3: "TJK",
    Numeric: 762,
  },
  {
    Country: "Tanzania, United Republic of",
    Code2: "TZ",
    Code3: "TZA",
    Numeric: 834,
  },
  {
    Country: "Thailand",
    Code2: "TH",
    Code3: "THA",
    Numeric: 764,
  },
  {
    Country: "Timor-Leste",
    Code2: "TL",
    Code3: "TLS",
    Numeric: 626,
  },
  {
    Country: "Togo",
    Code2: "TG",
    Code3: "TGO",
    Numeric: 768,
  },
  {
    Country: "Tokelau",
    Code2: "TK",
    Code3: "TKL",
    Numeric: 772,
  },
  {
    Country: "Tonga",
    Code2: "TO",
    Code3: "TON",
    Numeric: 776,
  },
  {
    Country: "Trinidad and Tobago",
    Code2: "TT",
    Code3: "TTO",
    Numeric: 780,
  },
  {
    Country: "Tunisia",
    Code2: "TN",
    Code3: "TUN",
    Numeric: 788,
  },
  {
    Country: "Turkey",
    Code2: "TR",
    Code3: "TUR",
    Numeric: 792,
  },
  {
    Country: "Turkmenistan",
    Code2: "TM",
    Code3: "TKM",
    Numeric: 795,
  },
  {
    Country: "Turks and Caicos Islands (the)",
    Code2: "TC",
    Code3: "TCA",
    Numeric: 796,
  },
  {
    Country: "Tuvalu",
    Code2: "TV",
    Code3: "TUV",
    Numeric: 798,
  },
  {
    Country: "Uganda",
    Code2: "UG",
    Code3: "UGA",
    Numeric: 800,
  },
  {
    Country: "Ukraine",
    Code2: "UA",
    Code3: "UKR",
    Numeric: 804,
  },
  {
    Country: "United Arab Emirates (the)",
    Code2: "AE",
    Code3: "ARE",
    Numeric: 784,
  },
  {
    Country: "United Kingdom of Great Britain and Northern Ireland (the)",
    Code2: "GB",
    Code3: "GBR",
    Numeric: 826,
  },
  {
    Country: "United States Minor Outlying Islands (the)",
    Code2: "UM",
    Code3: "UMI",
    Numeric: 581,
  },
  {
    Country: "United States of America (the)",
    Code2: "US",
    Code3: "USA",
    Numeric: 840,
  },
  {
    Country: "Uruguay",
    Code2: "UY",
    Code3: "URY",
    Numeric: 858,
  },
  {
    Country: "Uzbekistan",
    Code2: "UZ",
    Code3: "UZB",
    Numeric: 860,
  },
  {
    Country: "Vanuatu",
    Code2: "VU",
    Code3: "VUT",
    Numeric: 548,
  },
  {
    Country: "Venezuela (Bolivarian Republic of)",
    Code2: "VE",
    Code3: "VEN",
    Numeric: 862,
  },
  {
    Country: "Viet Nam",
    Code2: "VN",
    Code3: "VNM",
    Numeric: 704,
  },
  {
    Country: "Virgin Islands (British)",
    Code2: "VG",
    Code3: "VGB",
    Numeric: 92,
  },
  {
    Country: "Virgin Islands (U.S.)",
    Code2: "VI",
    Code3: "VIR",
    Numeric: 850,
  },
  {
    Country: "Wallis and Futuna",
    Code2: "WF",
    Code3: "WLF",
    Numeric: 876,
  },
  {
    Country: "Western Sahara",
    Code2: "EH",
    Code3: "ESH",
    Numeric: 732,
  },
  {
    Country: "Yemen",
    Code2: "YE",
    Code3: "YEM",
    Numeric: 887,
  },
  {
    Country: "Zambia",
    Code2: "ZM",
    Code3: "ZMB",
    Numeric: 894,
  },
  {
    Country: "Zimbabwe",
    Code2: "ZW",
    Code3: "ZWE",
    Numeric: 716,
  },
  {
    Country: "Åland Islands",
    Code2: "AX",
    Code3: "ALA",
    Numeric: 248,
  },
];
